### PR TITLE
Feat - added products page

### PR DESCRIPTION
**Pull request by Mohasin-Haque**
## Products Page
I have added the products page. It's still in the experimental phase. So ignore other files. Focus only on the products files.

Live Preview -

Files to check
- [x] Files which are named as Products. 
PS - Ignore other files. They are WIP. But you can comment on code used by products page components.

What not to check
- [ ] Images
- [ ] Functionalities
Here are some screen shots:-
products page

### CODE REVIEW

**Review by ivinayakg — APPROVED** [review]
good UI go ahead and merge it.

**Review by sahiba0915 — COMMENTED** [review]
Looks good, liked the way you structured the code.

**Review by arjunbharti — APPROVED** [review]
The UI look clean and nice.
Few suggestions:

- Don't repeat components, you can use map function instead
- import images in db file and access them using map function in your components

**Comment by Mohasin-Haque** [comment]
Thanks for the suggestion . I worked on the suggestions and would love to receive some thoughts on my approach.

**Pull request merged**
